<?php

use App\Http\Controllers\Api\AccessController;
use App\Http\Controllers\Api\AccountingController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\HealthController;
use App\Http\Controllers\Api\LookupController;
use App\Http\Controllers\Api\MasterDataController;
use App\Http\Controllers\Api\OperationsController;
use App\Http\Controllers\Api\PayablesController;
use App\Http\Controllers\Api\PlatformController;
use App\Http\Controllers\Api\PurchaseRequestController;
use App\Http\Controllers\Api\PurchasingController;
use App\Http\Controllers\Api\ReceivablesController;
use App\Http\Controllers\Api\ReceivingController;
use App\Http\Controllers\Api\ReportingController;
use App\Http\Controllers\Api\SalesController;
use App\Http\Controllers\Api\StockControlController;
use App\Http\Controllers\Api\WorkspaceDataController;
use Illuminate\Support\Facades\Route;

Route::get('/health', HealthController::class);
Route::post('/auth/login', [AuthController::class, 'login']);

Route::middleware('auth:sanctum')->group(function (): void {
    Route::get('/auth/me', [AuthController::class, 'me']);
    Route::post('/auth/logout', [AuthController::class, 'logout']);
    Route::get('/lookups/{resource}', LookupController::class);
    Route::get('/workspace-data/{resource}', [WorkspaceDataController::class, 'index']);
    Route::get('/workspace-data/{resource}/{id}', [WorkspaceDataController::class, 'show']);
    Route::patch('/workspace-data/{resource}/{id}', [WorkspaceDataController::class, 'update']);

    Route::prefix('master-data/{resource}')->group(function (): void {
        Route::get('/', [MasterDataController::class, 'index']);
        Route::post('/', [MasterDataController::class, 'store']);
        Route::get('/{id}', [MasterDataController::class, 'show']);
        Route::patch('/{id}', [MasterDataController::class, 'update']);
        Route::post('/{id}/archive', [MasterDataController::class, 'archive']);
    });

    Route::apiResource('purchase-requests', PurchaseRequestController::class)->only(['index', 'show', 'store']);
    Route::patch('/purchase-requests/{id}', [PurchaseRequestController::class, 'update']);
    Route::post('/purchase-requests/{id}/submit', [PurchaseRequestController::class, 'submit']);
    Route::post('/purchase-requests/{id}/cancel', [PurchaseRequestController::class, 'cancel']);

    Route::get('/rfqs', [PurchasingController::class, 'rfqs']);
    Route::post('/rfqs', [PurchasingController::class, 'storeRfq']);
    Route::get('/rfqs/{id}', [PurchasingController::class, 'showRfq']);
    Route::patch('/rfqs/{id}', [PurchasingController::class, 'updateRfq']);
    Route::post('/rfqs/{id}/submit', [PurchasingController::class, 'submitRfq']);
    Route::get('/supplier-quotations', [PurchasingController::class, 'quotations']);
    Route::post('/supplier-quotations', [PurchasingController::class, 'storeQuotation']);
    Route::post('/quotation-comparisons', [PurchasingController::class, 'compareQuotations']);
    Route::get('/purchase-orders', [PurchasingController::class, 'purchaseOrders']);
    Route::post('/purchase-orders', [PurchasingController::class, 'storePurchaseOrder']);
    Route::get('/goods-receipts', [ReceivingController::class, 'index']);
    Route::post('/goods-receipts', [ReceivingController::class, 'store']);
    Route::post('/goods-receipts/{id}/quality-check', [ReceivingController::class, 'qualityCheck']);
    Route::post('/goods-receipts/{id}/post', [ReceivingController::class, 'post']);
    Route::get('/stock', [ReceivingController::class, 'stock']);
    Route::get('/purchase-invoices', [PayablesController::class, 'invoices']);
    Route::post('/purchase-invoices', [PayablesController::class, 'storeInvoice']);
    Route::get('/payments', [PayablesController::class, 'payments']);
    Route::post('/payments', [PayablesController::class, 'storePayment']);
    Route::post('/sales-orders', [SalesController::class, 'storeOrder']);
    Route::post('/deliveries', [SalesController::class, 'storeDelivery']);
    Route::post('/sales-invoices', [SalesController::class, 'storeInvoice']);
    Route::get('/accounts', [AccountingController::class, 'accounts']);
    Route::post('/accounts', [AccountingController::class, 'storeAccount']);
    Route::get('/journals', [AccountingController::class, 'journals']);
    Route::post('/journals', [AccountingController::class, 'storeJournal']);
    Route::get('/reports/trial-balance', [AccountingController::class, 'trialBalance']);
    Route::post('/fiscal-periods/{id}/close', [AccountingController::class, 'closePeriod']);
    Route::post('/fiscal-periods/{id}/reopen', [AccountingController::class, 'reopenPeriod']);
    Route::post('/warehouse-bins', [OperationsController::class, 'createBin']);
    Route::post('/stock-counts', [OperationsController::class, 'createCount']);
    Route::post('/stock-counts/{id}/submit', [OperationsController::class, 'submitCount']);
    Route::post('/bank-accounts', [OperationsController::class, 'createBankAccount']);
    Route::post('/bank-statements', [OperationsController::class, 'createStatement']);
    Route::post('/bank-statement-lines/{id}/match', [OperationsController::class, 'matchStatementLine']);
    Route::post('/documents', [OperationsController::class, 'createDocument']);
    Route::post('/documents/{id}/attachments', [OperationsController::class, 'attach']);
    Route::post('/integration-logs', [OperationsController::class, 'integration']);
    Route::post('/sales-invoices/{id}/tax-snapshot', [ReceivablesController::class, 'storeInvoiceTax']);
    Route::post('/customer-receipts', [ReceivablesController::class, 'storeReceipt']);
    Route::post('/sales-returns', [ReceivablesController::class, 'storeReturn']);
    Route::post('/credit-notes', [ReceivablesController::class, 'storeCreditNote']);
    Route::post('/stock-transfers', [StockControlController::class, 'transfer']);
    Route::post('/stock-adjustments', [StockControlController::class, 'adjustment']);
    Route::post('/workflow-definitions', [PlatformController::class, 'createWorkflow']);
    Route::post('/workflow-instances', [PlatformController::class, 'startApproval']);
    Route::post('/approvals/{id}/decide', [PlatformController::class, 'decideApproval']);
    Route::get('/notifications', [PlatformController::class, 'notifications']);
    Route::post('/notifications/{id}/read', [PlatformController::class, 'readNotification']);
    Route::post('/leads', [PlatformController::class, 'storeLead']);
    Route::post('/opportunities', [PlatformController::class, 'storeOpportunity']);
    Route::post('/activities', [PlatformController::class, 'storeActivity']);
    Route::post('/projects', [PlatformController::class, 'storeProject']);
    Route::post('/projects/{projectId}/tasks', [PlatformController::class, 'storeTask']);
    Route::post('/service-tickets', [PlatformController::class, 'storeTicket']);
    Route::post('/report-jobs', [PlatformController::class, 'createReportJob']);
    Route::post('/import-jobs', [PlatformController::class, 'createImportJob']);
    Route::get('/roles', [AccessController::class, 'roles'])->middleware('permission:security.role.view');
    Route::post('/roles', [AccessController::class, 'createRole'])->middleware('permission:security.role.manage');
    Route::post('/users/{userId}/roles/{roleId}', [AccessController::class, 'assignRole'])->middleware('permission:security.role.manage');
    Route::get('/audit-events', [ReportingController::class, 'audit']);
    Route::get('/reports/ar-aging', [ReportingController::class, 'arAging']);
    Route::get('/reports/ap-aging', [ReportingController::class, 'apAging']);
    Route::get('/reports/inventory-summary', [ReportingController::class, 'inventorySummary']);
});
