export type Option = { label: string; value: string };
export type Field = {
  name: string; label: string; type?: 'text' | 'email' | 'password' | 'number' | 'date' | 'datetime-local' | 'textarea' | 'select' | 'boolean' | 'json';
  required?: boolean; options?: Option[]; lookup?: 'units' | 'items' | 'parties' | 'tax-codes' | 'companies' | 'branches' | 'warehouses' | 'users' | 'permissions'; lookupFilter?: 'customer' | 'supplier'; default?: string | number | boolean; placeholder?: string; help?: string;
};
export type LineGroup = { name: string; label: string; fields: Field[]; min?: number };
export type Resource = {
  slug: string; title: string; singular: string; group: string; description: string; icon: string;
  listPath?: string; showPath?: string; createPath?: string; updatePath?: string; method?: 'POST' | 'PATCH'; columns?: string[]; filters?: Field[]; fields?: Field[]; lines?: LineGroup[];
  actionLabel?: string; success?: string; responseNote?: string;
  updateStatuses?: string[];
};

const o = (...values: string[]): Option[] => values.map((value) => ({ value, label: value.replaceAll('_', ' ').replace(/^./, (c) => c.toUpperCase()) }));
const id = (name: string, label: string, lookup?: Field['lookup'], lookupFilter?: Field['lookupFilter']): Field => ({ name, label, required: true, lookup, lookupFilter, placeholder: lookup ? 'Pilih data' : 'UUID', help: lookup ? undefined : 'Masukkan UUID dari dokumen atau organisasi terkait.' });
const company = id('company_id', 'Company', 'companies');
const branch = id('branch_id', 'Branch', 'branches');
const warehouse = id('warehouse_id', 'Warehouse', 'warehouses');
const date = (name: string, label: string, required = true): Field => ({ name, label, type: 'date', required });
const money = (name: string, label: string, required = true): Field => ({ name, label, type: 'number', required, default: 0 });
const text = (name: string, label: string, required = true): Field => ({ name, label, required });
const note = (name = 'notes', label = 'Catatan'): Field => ({ name, label, type: 'textarea' });
const select = (name: string, label: string, values: string[], required = true): Field => ({ name, label, type: 'select', options: o(...values), required });
const itemLine = [id('item_id', 'Item', 'items'), id('unit_id', 'Unit', 'units'), money('quantity', 'Kuantitas'), note()];

export const resources: Resource[] = [
  { slug:'units', title:'Satuan', singular:'satuan', group:'Master Data', icon:'U', description:'Presisi dan satuan dasar transaksi.', listPath:'/master-data/units', createPath:'/master-data/units', columns:['code','name','precision','status'], filters:[text('search','Cari',false),select('status','Status',['active','inactive'],false)], fields:[text('code','Kode'),text('name','Nama'),{name:'precision',label:'Presisi',type:'number',required:true,default:0},select('status','Status',['active','inactive'],false)] },
  { slug:'items', title:'Item & Produk', singular:'item', group:'Master Data', icon:'I', description:'Katalog barang, jasa, aset, dan tracking.', listPath:'/master-data/items', createPath:'/master-data/items', columns:['sku','name','type','minimum_price','status'], filters:[text('search','Cari',false),select('status','Status',['active','inactive'],false)], fields:[text('sku','SKU'),text('name','Nama'),select('type','Tipe',['stock','service','asset']),id('base_unit_id','Satuan dasar','units'),{name:'lot_tracking',label:'Lot tracking',type:'boolean'},{name:'serial_tracking',label:'Serial tracking',type:'boolean'},{name:'expiry_tracking',label:'Expiry tracking',type:'boolean'},money('minimum_price','Harga minimum',false),{name:'metadata',label:'Metadata JSON',type:'json',default:'{}'}] },
  { slug:'parties', title:'Pelanggan & Supplier', singular:'party', group:'Master Data', icon:'P', description:'Mitra dagang dan batas kredit.', listPath:'/master-data/parties', createPath:'/master-data/parties', columns:['code','legal_name','type','email','phone','credit_limit','status'], filters:[text('search','Cari',false),select('status','Status',['active','inactive'],false)], fields:[text('code','Kode'),select('type','Tipe',['customer','supplier','both','person']),text('legal_name','Nama legal'),text('tax_id','NPWP / Tax ID',false),{name:'email',label:'Email',type:'email'},text('phone','Telepon',false),money('credit_limit','Batas kredit',false),select('status','Status',['active','inactive'],false)] },
  { slug:'tax-codes', title:'Kode Pajak', singular:'kode pajak', group:'Master Data', icon:'%', description:'Tarif pajak efektif per periode.', listPath:'/master-data/tax-codes', createPath:'/master-data/tax-codes', columns:['code','name','rate','effective_from','effective_to','status'], filters:[text('search','Cari',false),select('status','Status',['active','inactive'],false)], fields:[text('code','Kode'),text('name','Nama'),money('rate','Tarif (%)'),date('effective_from','Efektif mulai'),date('effective_to','Efektif sampai',false),select('status','Status',['active','inactive'],false)] },

  { slug:'purchase-requests', title:'Purchase Requests', singular:'purchase request', group:'Purchasing', icon:'PR', description:'Permintaan kebutuhan internal sebelum sourcing.', listPath:'/purchase-requests', createPath:'/purchase-requests', columns:['number','request_date','required_date','status','estimated_total'], filters:[select('status','Status',['draft','submitted','approved','cancelled'],false)], fields:[company,branch,date('request_date','Tanggal permintaan'),date('required_date','Dibutuhkan tanggal',false),note()], lines:[{name:'lines',label:'Item permintaan',fields:itemLine}] },
  { slug:'rfqs', title:'Request for Quotation', singular:'RFQ', group:'Purchasing', icon:'RQ', description:'Undang supplier dan minta penawaran.', listPath:'/rfqs', createPath:'/rfqs', columns:['number','request_date','quotation_deadline','status','purchase_request_id'], filters:[select('status','Status',['draft','sent'],false)], fields:[company,branch,id('purchase_request_id','Purchase Request ID'),date('request_date','Tanggal RFQ'),date('quotation_deadline','Batas penawaran',false),note()], lines:[{name:'lines',label:'Item RFQ',fields:itemLine},{name:'supplier_ids',label:'Supplier',fields:[id('value','Supplier','parties','supplier')]}] },
  { slug:'supplier-quotations', title:'Penawaran Supplier', singular:'penawaran', group:'Purchasing', icon:'SQ', description:'Catat harga, pajak, dan janji pengiriman supplier.', listPath:'/supplier-quotations', createPath:'/supplier-quotations', columns:['number','quotation_date','currency','payment_days','subtotal','tax_total','total','status'], filters:[text('rfq_id','RFQ ID',false)], fields:[company,id('rfq_id','RFQ ID'),id('supplier_id','Supplier','parties','supplier'),date('quotation_date','Tanggal penawaran'),date('valid_until','Berlaku sampai',false),text('currency','Mata uang'),{name:'payment_days',label:'Termin (hari)',type:'number',default:0},note()], lines:[{name:'lines',label:'Baris penawaran',fields:[id('rfq_line_id','RFQ Line ID'),money('quantity','Kuantitas'),money('unit_price','Harga satuan'),money('tax_rate','Pajak (%)',false),date('promised_date','Tanggal dijanjikan',false)]}] },
  { slug:'quotation-comparisons', title:'Perbandingan Penawaran', singular:'perbandingan', group:'Purchasing', icon:'QC', description:'Evaluasi penawaran dan tetapkan pemenang.', createPath:'/quotation-comparisons', fields:[company,id('rfq_id','RFQ ID'),id('selected_quotation_id','Penawaran terpilih'),note('decision_notes','Alasan keputusan')], lines:[{name:'quotation_ids',label:'Penawaran dibandingkan',fields:[id('value','Quotation ID')]}], actionLabel:'Setujui perbandingan' },
  { slug:'purchase-orders', title:'Purchase Orders', singular:'purchase order', group:'Purchasing', icon:'PO', description:'Pesanan pembelian dari penawaran terpilih.', listPath:'/purchase-orders', createPath:'/purchase-orders', columns:['number','order_date','expected_date','status','currency','total'], filters:[select('status','Status',['approved','partially_received','fully_received'],false)], fields:[company,branch,id('supplier_quotation_id','Supplier Quotation ID'),date('order_date','Tanggal pesanan'),date('expected_date','Ekspektasi tiba',false),note()] },
  { slug:'goods-receipts', title:'Penerimaan Barang', singular:'goods receipt', group:'Purchasing', icon:'GR', description:'Penerimaan, QC, dan posting stok.', listPath:'/goods-receipts', createPath:'/goods-receipts', columns:['number','receipt_date','status','warehouse_id','purchase_order_id'], fields:[id('purchase_order_id','Purchase Order ID'),warehouse,date('receipt_date','Tanggal diterima'),note()], lines:[{name:'lines',label:'Barang diterima',fields:[id('purchase_order_line_id','PO Line ID'),money('quantity','Kuantitas'),text('lot_number','Nomor lot',false),date('expiry_date','Kedaluwarsa',false)]}] },
  { slug:'goods-receipt-qc', title:'Quality Check', singular:'quality check', group:'Purchasing', icon:'QA', description:'Terima, tolak, atau pisahkan kuantitas penerimaan.', createPath:'/goods-receipts/{id}/quality-check', fields:[id('id','Goods Receipt ID'),select('result','Hasil',['passed','failed','partial']),note('reason','Alasan')], lines:[{name:'lines',label:'Hasil per baris',fields:[id('goods_receipt_line_id','Receipt Line ID'),money('accepted_quantity','Diterima'),money('rejected_quantity','Ditolak')]}], actionLabel:'Simpan hasil QC' },
  { slug:'goods-receipt-post', title:'Posting Penerimaan', singular:'posting penerimaan', group:'Purchasing', icon:'✓', description:'Posting penerimaan lolos QC ke stok dan jurnal.', createPath:'/goods-receipts/{id}/post', fields:[id('id','Goods Receipt ID')], actionLabel:'Posting penerimaan' },
  { slug:'purchase-invoices', title:'Invoice Supplier', singular:'invoice supplier', group:'Purchasing', icon:'PI', description:'Three-way match dan hutang usaha.', listPath:'/purchase-invoices', createPath:'/purchase-invoices', columns:['number','supplier_invoice_number','invoice_date','due_date','status','total'], fields:[company,id('purchase_order_id','Purchase Order ID'),text('supplier_invoice_number','Nomor invoice supplier'),date('invoice_date','Tanggal invoice'),date('due_date','Jatuh tempo',false),money('subtotal','Subtotal'),money('tax_total','Pajak'),money('total','Total'),note('match_notes','Catatan matching')] },
  { slug:'payments', title:'Pembayaran Supplier', singular:'pembayaran', group:'Purchasing', icon:'AP', description:'Alokasi pembayaran ke invoice supplier.', listPath:'/payments', createPath:'/payments', columns:['number','payment_date','method','amount','status'], fields:[company,date('payment_date','Tanggal pembayaran'),select('method','Metode',['bank','cash','petty_cash']),money('amount','Jumlah'),note()], lines:[{name:'allocations',label:'Alokasi invoice',fields:[id('purchase_invoice_id','Purchase Invoice ID'),money('amount','Jumlah')]}] },

  { slug:'sales-orders', title:'Sales Orders', singular:'sales order', group:'Sales', icon:'SO', description:'Pesanan pelanggan dan kalkulasi harga.', createPath:'/sales-orders', fields:[company,branch,id('customer_id','Pelanggan','parties','customer'),date('order_date','Tanggal pesanan')], lines:[{name:'lines',label:'Item penjualan',fields:[id('item_id','Item','items'),id('unit_id','Unit','units'),money('quantity','Kuantitas'),money('unit_price','Harga satuan'),money('tax_rate','Pajak (%)',false)]}] },
  { slug:'deliveries', title:'Delivery Orders', singular:'delivery', group:'Sales', icon:'DO', description:'Keluarkan stok untuk pesanan pelanggan.', createPath:'/deliveries', fields:[id('sales_order_id','Sales Order ID'),warehouse,date('delivery_date','Tanggal pengiriman')], lines:[{name:'lines',label:'Item dikirim',fields:[id('sales_order_line_id','Sales Order Line ID'),money('quantity','Kuantitas')]}] },
  { slug:'sales-invoices', title:'Sales Invoices', singular:'sales invoice', group:'Sales', icon:'SI', description:'Terbitkan piutang dari barang terkirim.', createPath:'/sales-invoices', fields:[id('sales_order_id','Sales Order ID'),date('invoice_date','Tanggal invoice'),date('due_date','Jatuh tempo',false)] },
  { slug:'invoice-tax', title:'Snapshot Pajak Invoice', singular:'snapshot pajak', group:'Sales', icon:'TX', description:'Kunci tarif pajak efektif pada invoice.', createPath:'/sales-invoices/{id}/tax-snapshot', fields:[id('id','Sales Invoice ID')], lines:[{name:'tax_lines',label:'Baris pajak',fields:[id('tax_code_id','Kode pajak','tax-codes' as Field['lookup']),money('taxable_amount','Dasar pengenaan')]}], actionLabel:'Simpan snapshot pajak' },
  { slug:'customer-receipts', title:'Penerimaan Pelanggan', singular:'penerimaan', group:'Sales', icon:'AR', description:'Alokasi pembayaran masuk ke invoice pelanggan.', createPath:'/customer-receipts', fields:[company,id('customer_id','Pelanggan','parties','customer'),date('receipt_date','Tanggal penerimaan'),select('method','Metode',['bank','cash','petty_cash']),money('amount','Jumlah')], lines:[{name:'allocations',label:'Alokasi invoice',fields:[id('sales_invoice_id','Sales Invoice ID'),money('amount','Jumlah')]}] },
  { slug:'sales-returns', title:'Retur Penjualan', singular:'retur', group:'Sales', icon:'RT', description:'Kembalikan barang pelanggan ke gudang.', createPath:'/sales-returns', fields:[company,branch,warehouse,id('sales_order_id','Sales Order ID'),{...id('sales_invoice_id','Sales Invoice ID'),required:false},date('return_date','Tanggal retur'),note('reason','Alasan')], lines:[{name:'lines',label:'Item retur',fields:[id('sales_order_line_id','Sales Order Line ID'),money('quantity','Kuantitas')]}] },
  { slug:'credit-notes', title:'Credit Notes', singular:'credit note', group:'Sales', icon:'CN', description:'Kredit pelanggan dari retur terposting.', createPath:'/credit-notes', fields:[company,id('sales_invoice_id','Sales Invoice ID'),id('sales_return_id','Sales Return ID'),date('credit_date','Tanggal kredit'),note('reason','Alasan')] },

  { slug:'stock', title:'Stock On Hand', singular:'saldo stok', group:'Inventory', icon:'ST', description:'Saldo, reservasi, biaya rata-rata, dan nilai stok.', listPath:'/stock', columns:['warehouse_id','item_id','on_hand','reserved','average_cost'], filters:[text('warehouse_id','Warehouse ID',false),text('item_id','Item ID',false)] },
  { slug:'stock-transfers', title:'Transfer Gudang', singular:'transfer', group:'Inventory', icon:'TR', description:'Pindahkan stok antar gudang dalam satu company.', createPath:'/stock-transfers', fields:[company,id('source_warehouse_id','Gudang asal'),id('destination_warehouse_id','Gudang tujuan'),date('transfer_date','Tanggal transfer'),note('reason','Alasan')], lines:[{name:'lines',label:'Item transfer',fields:[id('item_id','Item','items'),id('unit_id','Unit','units'),money('quantity','Kuantitas')]}] },
  { slug:'stock-adjustments', title:'Penyesuaian Stok', singular:'adjustment', group:'Inventory', icon:'AD', description:'Koreksi stok dengan jejak ledger.', createPath:'/stock-adjustments', fields:[company,warehouse,date('adjustment_date','Tanggal adjustment'),note('reason','Alasan')], lines:[{name:'lines',label:'Item adjustment',fields:[id('item_id','Item','items'),id('unit_id','Unit','units'),money('quantity_delta','Selisih kuantitas'),money('unit_cost','Biaya satuan',false)]}] },
  { slug:'warehouse-bins', title:'Warehouse Bins', singular:'bin', group:'Inventory', icon:'WB', description:'Lokasi rak dan bin di gudang.', createPath:'/warehouse-bins', fields:[warehouse,text('code','Kode bin'),text('name','Nama bin')] },
  { slug:'stock-counts', title:'Stock Opname', singular:'stock count', group:'Inventory', icon:'SC', description:'Buat cycle count atau opname fisik.', createPath:'/stock-counts', fields:[warehouse,select('count_type','Tipe',['cycle','opname']),date('count_date','Tanggal hitung'),note('reason','Alasan')], lines:[{name:'item_ids',label:'Item dihitung',fields:[id('value','Item','items')]}] },
  { slug:'stock-count-submit', title:'Posting Stock Count', singular:'posting count', group:'Inventory', icon:'PC', description:'Masukkan hasil fisik dan posting variance.', createPath:'/stock-counts/{id}/submit', fields:[id('id','Stock Count ID')], lines:[{name:'lines',label:'Hasil hitung',fields:[id('id','Stock Count Line ID'),money('counted_quantity','Kuantitas fisik')]}], actionLabel:'Posting hasil count' },

  { slug:'accounts', title:'Chart of Accounts', singular:'akun', group:'Finance', icon:'COA', description:'Struktur akun perusahaan.', listPath:'/accounts', createPath:'/accounts', columns:['code','name','type','normal_balance','status'], fields:[text('code','Kode akun'),text('name','Nama akun'),select('type','Tipe',['asset','liability','equity','revenue','expense']),select('normal_balance','Saldo normal',['debit','credit']),{...id('parent_id','Parent Account ID'),required:false}] },
  { slug:'journals', title:'General Journals', singular:'jurnal', group:'Finance', icon:'JV', description:'Jurnal manual double-entry.', listPath:'/journals', createPath:'/journals', columns:['number','journal_date','description','status','source_type'], fields:[date('journal_date','Tanggal jurnal'),note('description','Deskripsi')], lines:[{name:'lines',label:'Baris jurnal',min:2,fields:[id('account_id','Account ID'),money('debit','Debit',false),money('credit','Kredit',false),text('description','Deskripsi',false)]}] },
  { slug:'trial-balance', title:'Trial Balance', singular:'trial balance', group:'Finance', icon:'TB', description:'Saldo debit dan kredit per akun.', listPath:'/reports/trial-balance', columns:['code','name','debit','credit'] },
  { slug:'ar-aging', title:'AR Aging', singular:'AR aging', group:'Finance', icon:'AR', description:'Umur piutang pelanggan.', listPath:'/reports/ar-aging', columns:['number','customer_id','total','bucket'], responseNote:'Laporan dikelompokkan ke current, 1-30, 31-60, 61-90, dan 90+ hari.' },
  { slug:'ap-aging', title:'AP Aging', singular:'AP aging', group:'Finance', icon:'AP', description:'Umur hutang supplier.', listPath:'/reports/ap-aging', columns:['number','supplier_id','total','bucket'] },
  { slug:'inventory-summary', title:'Inventory Summary', singular:'ringkasan inventory', group:'Finance', icon:'IV', description:'Nilai persediaan per gudang.', listPath:'/reports/inventory-summary', columns:['warehouse_id','sku_count','total_units','total_value'] },
  { slug:'fiscal-period-close', title:'Tutup Periode', singular:'periode', group:'Finance', icon:'CL', description:'Tutup periode fiskal untuk mencegah posting.', createPath:'/fiscal-periods/{id}/close', fields:[id('id','Fiscal Period ID')], actionLabel:'Tutup periode' },
  { slug:'fiscal-period-reopen', title:'Buka Kembali Periode', singular:'periode', group:'Finance', icon:'OP', description:'Aktifkan kembali periode tertutup.', createPath:'/fiscal-periods/{id}/reopen', fields:[id('id','Fiscal Period ID')], actionLabel:'Buka kembali periode' },
  { slug:'bank-accounts', title:'Rekening Bank', singular:'rekening', group:'Finance', icon:'BA', description:'Rekening bank perusahaan.', createPath:'/bank-accounts', fields:[company,text('code','Kode'),text('name','Nama rekening'),text('bank_name','Nama bank',false),text('account_number','Nomor rekening',false),{...text('currency','Mata uang'),default:'IDR'}] },
  { slug:'bank-statements', title:'Bank Statements', singular:'bank statement', group:'Finance', icon:'BS', description:'Impor baris mutasi bank untuk rekonsiliasi.', createPath:'/bank-statements', fields:[id('bank_account_id','Bank Account ID'),text('statement_number','Nomor statement'),date('statement_date','Tanggal statement'),money('opening_balance','Saldo awal',false),money('closing_balance','Saldo akhir',false)], lines:[{name:'lines',label:'Mutasi bank',fields:[date('transaction_date','Tanggal'),text('reference','Referensi',false),text('description','Deskripsi',false),money('amount','Jumlah'),select('direction','Arah',['in','out'])]}] },
  { slug:'bank-match', title:'Bank Reconciliation', singular:'matching', group:'Finance', icon:'BR', description:'Cocokkan baris statement dengan payment.', createPath:'/bank-statement-lines/{id}/match', fields:[id('id','Bank Statement Line ID'),id('payment_id','Payment ID')], actionLabel:'Match payment' },

  { slug:'leads', title:'Leads', singular:'lead', group:'CRM & Service', icon:'LD', description:'Prospek baru dari berbagai sumber.', createPath:'/leads', fields:[text('name','Nama'),{name:'email',label:'Email',type:'email'},text('phone','Telepon',false),text('source','Sumber',false)] },
  { slug:'opportunities', title:'Opportunities', singular:'opportunity', group:'CRM & Service', icon:'OP', description:'Pipeline peluang dan probabilitas.', createPath:'/opportunities', fields:[text('name','Nama'),{...id('customer_id','Pelanggan','parties','customer'),required:false},money('expected_value','Nilai ekspektasi',false),{name:'probability',label:'Probabilitas (%)',type:'number',default:0},date('expected_close_date','Target closing',false)] },
  { slug:'activities', title:'Activities', singular:'aktivitas', group:'CRM & Service', icon:'AC', description:'Call, email, meeting, task, dan note.', createPath:'/activities', fields:[text('subject','Subjek'),select('activity_type','Tipe',['call','email','meeting','task','note']),{name:'due_at',label:'Jatuh tempo',type:'datetime-local'},note(),text('related_type','Tipe relasi',false),{...id('related_id','Entity terkait'),required:false}] },
  { slug:'projects', title:'Projects', singular:'project', group:'CRM & Service', icon:'PJ', description:'Budget dan timeline project.', createPath:'/projects', fields:[company,text('code','Kode'),text('name','Nama'),date('start_date','Mulai',false),date('end_date','Selesai',false),money('budget','Budget',false)] },
  { slug:'project-tasks', title:'Project Tasks', singular:'task', group:'CRM & Service', icon:'PT', description:'Tambahkan pekerjaan pada project.', createPath:'/projects/{projectId}/tasks', fields:[id('projectId','Project ID'),text('name','Nama task'),{...id('assignee_id','Assignee User ID'),required:false},date('due_date','Jatuh tempo',false)] },
  { slug:'service-tickets', title:'Service Tickets', singular:'ticket', group:'CRM & Service', icon:'TK', description:'Keluhan dan permintaan pelanggan.', createPath:'/service-tickets', fields:[id('customer_id','Pelanggan','parties','customer'),text('subject','Subjek'),select('priority','Prioritas',['low','normal','high','urgent'],false),note('description','Deskripsi')] },

  { slug:'workflow-definitions', title:'Workflow Definitions', singular:'workflow', group:'Platform', icon:'WF', description:'Rangkaian approver untuk tipe dokumen.', createPath:'/workflow-definitions', fields:[text('entity_type','Tipe entity'),text('name','Nama workflow')], lines:[{name:'steps',label:'Tahap approval',fields:[id('approver_id','Approver User ID')]}] },
  { slug:'workflow-instances', title:'Start Approval', singular:'approval', group:'Platform', icon:'WA', description:'Mulai approval pada sebuah entity.', createPath:'/workflow-instances', fields:[id('definition_id','Workflow Definition ID'),text('entity_type','Tipe entity'),id('entity_id','Entity ID')] },
  { slug:'approval-decisions', title:'Approval Decision', singular:'keputusan', group:'Platform', icon:'✓', description:'Setujui atau tolak approval yang ditugaskan.', createPath:'/approvals/{id}/decide', fields:[id('id','Approval ID'),select('decision','Keputusan',['approved','rejected']),note('comment','Komentar')], actionLabel:'Kirim keputusan' },
  { slug:'notifications', title:'Notifications', singular:'notifikasi', group:'Platform', icon:'NT', description:'Pemberitahuan approval dan sistem.', listPath:'/notifications', columns:['title','body','type','status','created_at'] },
  { slug:'notification-read', title:'Mark Notification Read', singular:'notifikasi', group:'Platform', icon:'NR', description:'Tandai notifikasi sebagai dibaca.', createPath:'/notifications/{id}/read', fields:[id('id','Notification ID')], actionLabel:'Tandai dibaca' },
  { slug:'roles', title:'Roles & Permissions', singular:'role', group:'Platform', icon:'RB', description:'Role tenant dan permission keys.', listPath:'/roles', createPath:'/roles', columns:['code','name','status','created_at'], fields:[text('code','Kode'),text('name','Nama')], lines:[{name:'permission_keys',label:'Permission key',fields:[text('value','Permission key')]}] },
  { slug:'role-assignments', title:'Assign User Role', singular:'assignment', group:'Platform', icon:'RA', description:'Pasang role kepada user tenant.', createPath:'/users/{userId}/roles/{roleId}', fields:[id('userId','User ID'),id('roleId','Role ID')], actionLabel:'Assign role' },
  { slug:'audit-events', title:'Audit Trail', singular:'audit event', group:'Platform', icon:'AU', description:'Jejak perubahan dan tindakan pengguna.', listPath:'/audit-events', columns:['occurred_at','action','entity_type','entity_id','actor_id','ip_address'] },
  { slug:'documents', title:'Documents', singular:'document', group:'Platform', icon:'DC', description:'Metadata dokumen terkait entity.', createPath:'/documents', fields:[text('entity_type','Tipe entity'),id('entity_id','Entity ID'),text('document_type','Tipe dokumen'),text('title','Judul')] },
  { slug:'attachments', title:'Attachments', singular:'attachment', group:'Platform', icon:'AT', description:'Metadata file pada dokumen.', createPath:'/documents/{id}/attachments', fields:[id('id','Document ID'),text('file_name','Nama file'),text('storage_path','Storage path'),text('mime_type','MIME type',false),{name:'size',label:'Ukuran byte',type:'number',default:0},text('sha256','SHA-256',false)] },
  { slug:'integrations', title:'Integration Intake', singular:'integration log', group:'Platform', icon:'IN', description:'Queue payload idempotent untuk integrasi.', createPath:'/integration-logs', fields:[text('provider','Provider'),select('direction','Arah',['inbound','outbound']),text('idempotency_key','Idempotency key'),{name:'request_payload',label:'Request payload JSON',type:'json',default:'{}'}], responseNote:'Request duplicate mengembalikan log yang sudah ada.' },
  { slug:'report-jobs', title:'Report Jobs', singular:'report job', group:'Platform', icon:'RJ', description:'Antrekan export laporan.', createPath:'/report-jobs', fields:[text('report_key','Report key'),select('format','Format',['xlsx','csv','pdf']),{name:'filters',label:'Filter JSON',type:'json',default:'{}'}], actionLabel:'Antrekan laporan' },
  { slug:'import-jobs', title:'Import Jobs', singular:'import job', group:'Platform', icon:'IM', description:'Antrekan import dari storage path.', createPath:'/import-jobs', fields:[text('import_type','Tipe import'),text('file_path','File path')], actionLabel:'Antrekan import' },
];

export const resourceMap = new Map(resources.map((resource) => [resource.slug, resource]));
export const groups = [...new Set(resources.map((resource) => resource.group))];

const readable = new Set(['quotation-comparisons','sales-orders','deliveries','sales-invoices','customer-receipts','sales-returns','credit-notes','stock-transfers','stock-adjustments','warehouse-bins','stock-counts','bank-accounts','bank-statements','leads','opportunities','activities','projects','service-tickets','workflow-definitions','workflow-instances','documents','integrations','report-jobs','import-jobs']);
const mutable = new Set(['warehouse-bins','bank-accounts','accounts','leads','opportunities','activities','projects','service-tickets','documents']);
const master = new Set(['units','items','parties','tax-codes']);

for (const resource of resources) {
  if (readable.has(resource.slug)) {
    resource.listPath = `/workspace-data/${resource.slug}`;
    resource.showPath = `/workspace-data/${resource.slug}/{id}`;
    resource.columns ??= resource.slug === 'warehouse-bins' ? ['code','name','status'] : resource.slug === 'leads' ? ['name','email','phone','status'] : resource.slug === 'activities' ? ['subject','activity_type','due_at','status'] : resource.slug === 'projects' ? ['code','name','status','budget'] : resource.slug === 'service-tickets' ? ['number','subject','priority','status'] : ['number','created_at','status'];
    resource.filters ??= [text('search','Cari',false), text('status','Status',false)];
  }
  if (mutable.has(resource.slug)) resource.updatePath = `/workspace-data/${resource.slug}/{id}`;
  if (master.has(resource.slug)) {
    resource.showPath = `/master-data/${resource.slug}/{id}`;
    resource.updatePath = `/master-data/${resource.slug}/{id}`;
  }
}
for (const slug of ['purchase-requests','rfqs']) {
  const resource = resources.find((item) => item.slug === slug)!;
  resource.showPath = slug === 'rfqs' ? '/rfqs/{id}' : '/purchase-requests/{id}';
  resource.updatePath = slug === 'rfqs' ? '/rfqs/{id}' : '/purchase-requests/{id}';
  resource.updateStatuses = ['draft'];
}
